local M = {}

local function esc(value)
    return (tostring(value or ""):gsub("|", "\\|"):gsub("\n", " "))
end

-- Every mode a user can map in. "v" maps are stored as x + s, and plain `:map`
-- maps show up under n/x/s/o, so results are de-duplicated below.
local MODES = { "n", "x", "s", "o", "i", "t", "c" }

local function label(map)
    if map.desc and map.desc ~= "" then
        return map.desc
    end
    if map.rhs == "<Nop>" then
        return "(disabled)"
    end
    return ""
end

local function get_keymaps()
    local seen, maps = {}, {}
    for _, mode in ipairs(MODES) do
        local ok, list = pcall(vim.api.nvim_get_keymap, mode)
        if ok then
            for _, map in ipairs(list) do
                local id = table.concat({ map.mode or "", map.lhsraw or map.lhs or "", map.desc or "" }, "\0")
                if not seen[id] and not (map.lhs or ""):match("^<Plug>") then
                    seen[id] = true
                    table.insert(maps, map)
                end
            end
        end
    end

    table.sort(maps, function(a, b)
        if a.mode == b.mode then
            return (a.lhs or "") < (b.lhs or "")
        end
        return (a.mode or "") < (b.mode or "")
    end)

    return maps
end

-- Buffer-local maps (LSP, nvim-tree, ...) exist only for the buffers open right now.
local function get_buffer_keymaps()
    local seen, out = {}, {}
    for _, buf in ipairs(vim.api.nvim_list_bufs()) do
        if vim.api.nvim_buf_is_loaded(buf) then
            local where = vim.bo[buf].filetype
            if where == "" then
                where = vim.fs.basename(vim.api.nvim_buf_get_name(buf))
            end
            for _, mode in ipairs(MODES) do
                local ok, list = pcall(vim.api.nvim_buf_get_keymap, buf, mode)
                if ok then
                    for _, map in ipairs(list) do
                        local id = table.concat({ where, map.mode or "", map.lhsraw or map.lhs or "", map.desc or "" }, "\0")
                        if not seen[id] and map.lhs and map.lhs ~= "" then
                            seen[id] = true
                            table.insert(out, { where = where, map = map })
                        end
                    end
                end
            end
        end
    end
    table.sort(out, function(a, b)
        if a.where == b.where then
            return (a.map.lhs or "") < (b.map.lhs or "")
        end
        return a.where < b.where
    end)
    return out
end

local function get_commands()
    local ok, commands = pcall(vim.api.nvim_get_commands, { builtin = false })
    if not ok then
        return {}
    end

    local result = {}
    for name, command in pairs(commands) do
        table.insert(result, {
            name = name,
            desc = command.desc or command.definition or "",
        })
    end

    table.sort(result, function(a, b)
        return a.name < b.name
    end)

    return result
end

local function get_lazy_stats()
    local ok, lazy = pcall(require, "lazy")
    if not ok then
        return nil
    end

    local ok_stats, stats = pcall(lazy.stats)
    if not ok_stats then
        return nil
    end

    return stats
end

local function generate_lines()
    local version = vim.version()
    local lines = {
        "# Loki Neovim IDE — Live Cheatsheet",
        "",
        "> Generated from the running Neovim environment. Do not edit this file manually.",
        "",
        "## Quick discovery",
        "",
        "| Action | How |",
        "| --- | --- |",
    }

    -- Generated from util/registry.lua, so it cannot drift from the real keys and commands.
    local registry = require("util.registry")
    for _, k in ipairs({ { "n", "<leader>?" }, { "n", "<leader>fk" }, { "n", "<leader>fc" }, { "n", "<leader>fh" },
        { "n", "<leader>fi" }, { "n", "<leader>fC" } }) do
        local e = registry.key(k[1], k[2])
        if e then
            table.insert(lines, string.format("| %s | `%s` |", esc(e.desc), esc(k[2])))
        end
    end
    for _, c in ipairs(registry.commands) do
        table.insert(lines, string.format("| %s | `:%s%s` |", esc(c.desc), esc(c.name), c.args and (" " .. esc(c.args)) or ""))
    end
    table.insert(lines, "| Check your setup | `:checkhealth loki` |")
    table.insert(lines, "| Built-in Neovim/Vim documentation | `:help` |")
    vim.list_extend(lines, {
        "",
        "## Leader namespaces",
        "",
        "| Key | Group |",
        "| --- | --- |",
    })

    for _, group in ipairs(require("config.leader_groups").all()) do
        table.insert(lines, string.format(
            "| `<leader>%s` | %s |",
            esc(group.key),
            esc(group.label)
        ))
    end

    local ok_kg, kg = pcall(require, "util.keyguard")
    if ok_kg then
        local overrides = kg.overrides_grouped()
        if #overrides > 0 then
            table.insert(lines, "")
            table.insert(lines, "## Shipped keys your keymaps replaced")
            table.insert(lines, "")
            table.insert(lines, "| Mode | Key | Shipped action | Now |")
            table.insert(lines, "| --- | --- | --- | --- |")
            for _, o in ipairs(overrides) do
                table.insert(lines, string.format("| `%s` | `%s` | %s | %s |",
                    esc(o.modes), esc(o.lhs), esc(o.was), esc(o.now)))
            end
        end
    end

    table.insert(lines, "")
    table.insert(lines, "## Registered keymaps")
    table.insert(lines, "")
    table.insert(lines, "Normal, select, operator-pending, insert, terminal and command-line modes")
    table.insert(lines, "(`v` means visual and select). Buffer-local keys are listed further down.")
    table.insert(lines, "")
    table.insert(lines, "| Mode | Key | Description |")
    table.insert(lines, "| --- | --- | --- |")

    for _, map in ipairs(get_keymaps()) do
        if map.lhs and map.lhs ~= "" then
            table.insert(lines, string.format(
                "| `%s` | `%s` | %s |",
                esc(map.mode),
                esc(map.lhs),
                esc(label(map))
            ))
        end
    end

    local buffer_maps = get_buffer_keymaps()
    if #buffer_maps > 0 then
        table.insert(lines, "")
        table.insert(lines, "## Buffer-local keymaps (buffers open when this was generated)")
        table.insert(lines, "")
        table.insert(lines, "| Buffer | Mode | Key | Description |")
        table.insert(lines, "| --- | --- | --- | --- |")
        for _, item in ipairs(buffer_maps) do
            table.insert(lines, string.format(
                "| `%s` | `%s` | `%s` | %s |",
                esc(item.where),
                esc(item.map.mode),
                esc(item.map.lhs),
                esc(label(item.map))
            ))
        end
    end

    table.insert(lines, "")
    table.insert(lines, "## User/plugin Ex commands")
    table.insert(lines, "")
    table.insert(lines, "| Command | Description |")
    table.insert(lines, "| --- | --- |")

    for _, command in ipairs(get_commands()) do
        table.insert(lines, string.format(
            "| `:%s` | %s |",
            esc(command.name),
            esc(command.desc)
        ))
    end

    table.insert(lines, "")
    table.insert(lines, "## Environment")
    table.insert(lines, "")
    table.insert(lines, "| Item | Value |")
    table.insert(lines, "| --- | --- |")
    table.insert(lines, string.format("| Neovim | `%d.%d.%d` |", version.major, version.minor, version.patch))
    table.insert(lines, string.format("| Config | `%s` |", vim.fn.stdpath("config")))
    table.insert(lines, string.format("| Data | `%s` |", vim.fn.stdpath("data")))

    local stats = get_lazy_stats()
    if stats then
        table.insert(lines, string.format(
            "| Lazy plugins | `%d loaded / %d total` |",
            stats.loaded or 0,
            stats.count or 0
        ))
    end

    local clients = vim.lsp.get_clients()
    table.insert(lines, "")
    table.insert(lines, "## LSP servers currently attached")
    table.insert(lines, "")
    if #clients == 0 then
        table.insert(lines, "No LSP clients are currently attached.")
    else
        table.insert(lines, "| Server | Root |")
        table.insert(lines, "| --- | --- |")
        for _, client in ipairs(clients) do
            table.insert(lines, string.format(
                "| `%s` | `%s` |",
                esc(client.name),
                esc(client.root_dir or "")
            ))
        end
    end

    table.insert(lines, "")
    table.insert(lines, "## Built-in documentation")
    table.insert(lines, "")
    table.insert(lines,
        "The complete built-in Vim/Neovim command and key documentation is intentionally not copied into this generated file.")
    table.insert(lines, "Use `:help`, `:help index`, `:help normal-index`, `:help insert-index`, and `:help :commands`.")
    table.insert(lines, "This keeps the generated sheet focused on what this particular environment adds and configures.")

    return lines
end

-- The cheatsheet lives in Neovim's state folder, not in the repo: it contains
-- machine-specific paths and changes on every start, which would keep git dirty.
function M.path()
    return vim.fn.stdpath("state") .. "/cheatsheet.md"
end

function M.generate()
    local path = M.path()
    vim.fn.mkdir(vim.fn.fnamemodify(path, ":h"), "p")

    -- Write a temp file, then rename, so two Neovims never leave a half-written sheet.
    local tmp = path .. "." .. vim.uv.os_getpid() .. ".tmp"
    local file = assert(io.open(tmp, "w"))
    file:write(table.concat(generate_lines(), "\n"))
    file:write("\n")
    file:close()
    assert(os.rename(tmp, path))

    return path
end

function M.setup()
    if vim.g.loki_cheatsheet_setup then
        return
    end
    vim.g.loki_cheatsheet_setup = true

    vim.api.nvim_create_user_command("Cheatsheet", function()
        local path = M.generate()
        vim.cmd("edit " .. vim.fn.fnameescape(path))
    end, { desc = require("util.registry").command_desc("Cheatsheet") })

    vim.api.nvim_create_user_command("CheatsheetUpdate", function()
        local path = M.generate()
        vim.notify("Cheatsheet updated: " .. path)
    end, { desc = require("util.registry").command_desc("CheatsheetUpdate") })

    vim.api.nvim_create_autocmd("User", {
        pattern = "LazyDone",
        callback = function()
            pcall(M.generate)
        end,
    })

    vim.api.nvim_create_autocmd("BufWritePost", {
        pattern = "*.lua",
        callback = function(args)
            local cfg = vim.fn.stdpath("config")
            local config = (vim.uv.fs_realpath(cfg) or cfg) .. "/"
            local file = vim.uv.fs_realpath(args.file) or args.file

            if file:sub(1, #config) == config then
                vim.defer_fn(function() pcall(M.generate) end, 100)
            end
        end,
    })

    -- Generate just after startup, not during it. Headless runs that quit
    -- immediately skip this (scripts/generate-cheatsheet.sh calls generate()).
    vim.api.nvim_create_autocmd("VimEnter", {
        once = true,
        callback = function()
            vim.defer_fn(function() pcall(M.generate) end, 200)
        end,
    })
end
 
return M
