#!/usr/bin/env bash
# Loki Neovim installer.
#
#   scripts/install.sh                interactive (asks if you already have a config)
#   scripts/install.sh --alongside    install as `nvim-loki`; nothing of yours is touched
#   scripts/install.sh --replace      become your `nvim` config (old one is backed up)
#   scripts/install.sh --dry-run      show what would happen, change nothing
#
# Undo with scripts/uninstall.sh.
set -euo pipefail

SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
BIN_DIR="$HOME/.local/bin"
LAUNCHER_MARK="# Generated by the Loki Neovim installer"

# Neovim creates ~/.local/state/nvim the first time it runs (even for --version).
# Take note of what existed *before* we run it, so we only warn about real leftovers.
PRE_EXISTING=()
for d in "$DATA_HOME/nvim" "$STATE_HOME/nvim" "$CACHE_HOME/nvim"; do
    [[ -e "$d" ]] && PRE_EXISTING+=("$d")
done

MODE=""
APPNAME=""
DRY_RUN=0
CLEAN_DATA=0
ASSUME_YES=0

say()  { printf '%s\n' "$*"; }
warn() { printf 'WARNING: %s\n' "$*" >&2; }
die()  { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
run()  { if ((DRY_RUN)); then say "  [dry-run] $*"; else "$@"; fi; }

usage() {
    cat <<'EOF'
Usage: scripts/install.sh [options]

  --alongside       Install as its own app (default name: loki). Launch it with
                    `nvim-loki`. Your current `nvim` config is not touched.
  --replace         Make this your `nvim` config. An existing config is moved to
                    ~/.config/nvim.backup.<timestamp>, never deleted.
  --appname NAME    Use NAME instead of "loki" (implies --alongside).
  --clean-data      With --replace: also move old plugin data, state and cache
                    (~/.local/share|state|cache/nvim) to timestamped backups so
                    leftovers from an old setup cannot interfere.
  --dry-run         Print what would happen and change nothing.
  -y, --yes         Do not ask questions (existing config => install alongside).
  -h, --help        Show this help.

Full guide (every flag, scenarios, troubleshooting): docs/INSTALL.md
EOF
}

while (($#)); do
    case "$1" in
        --replace)    MODE="replace" ;;
        --alongside)  MODE="alongside" ;;
        --appname)    shift; [[ $# -gt 0 ]] || die "--appname needs a value"
                      APPNAME="$1"; [[ -n "$MODE" ]] || MODE="alongside" ;;
        --clean-data) CLEAN_DATA=1 ;;
        --dry-run)    DRY_RUN=1 ;;
        -y|--yes)     ASSUME_YES=1 ;;
        -h|--help)    usage; exit 0 ;;
        *)            die "Unknown option: $1 (try --help)" ;;
    esac
    shift
done

say "== Loki Neovim installer =="
((DRY_RUN)) && say "(dry run: nothing will be changed)"

# --- Requirements -----------------------------------------------------------

command -v nvim >/dev/null 2>&1 || die "Neovim is not installed."
command -v git  >/dev/null 2>&1 || die "git is required."

NVIM_VERSION_LINE="$(nvim --version | head -n1)"
say "Detected: $NVIM_VERSION_LINE"
if [[ "$NVIM_VERSION_LINE" =~ v([0-9]+)\.([0-9]+) ]]; then
    if ((BASH_REMATCH[1] == 0 && BASH_REMATCH[2] < 11)); then
        die "Neovim 0.11 or newer is required (found: $NVIM_VERSION_LINE)."
    fi
fi

missing=()
for tool in rg make curl unzip node npm python3; do
    command -v "$tool" >/dev/null 2>&1 || missing+=("$tool")
done
if ! { command -v cc >/dev/null 2>&1 || command -v gcc >/dev/null 2>&1 || command -v clang >/dev/null 2>&1; }; then
    missing+=("a C compiler (gcc)")
fi
if ! { command -v wl-copy >/dev/null 2>&1 || command -v xclip >/dev/null 2>&1 \
    || command -v xsel >/dev/null 2>&1 || command -v win32yank.exe >/dev/null 2>&1; }; then
    missing+=("a clipboard tool (wl-clipboard or xclip)")
fi
if ((${#missing[@]})); then
    warn "Not found: ${missing[*]}"
    say "  The config still installs, but some features will not work until these"
    say "  are installed (see docs/README.md). Check later with :checkhealth loki"
fi

# --- Decide the mode --------------------------------------------------------

DEFAULT_TARGET="$CONFIG_HOME/nvim"
has_existing=0
if [[ -e "$DEFAULT_TARGET" ]]; then
    [[ "$(readlink -f "$DEFAULT_TARGET")" == "$SOURCE_DIR" ]] || has_existing=1
fi

if [[ -z "$MODE" ]]; then
    if ((has_existing)); then
        if [[ -t 0 && $ASSUME_YES -eq 0 ]]; then
            say
            say "You already have a Neovim config at $DEFAULT_TARGET."
            say "  1) Install alongside  -> run it with \`nvim-loki\`; your config is not touched (recommended)"
            say "  2) Replace            -> this becomes \`nvim\`; your old config is moved to a backup"
            say "  3) Cancel"
            read -r -p "Choose [1/2/3, default 1]: " choice
            case "${choice:-1}" in
                1) MODE="alongside" ;;
                2) MODE="replace" ;;
                *) say "Cancelled. Nothing was changed."; exit 0 ;;
            esac
        else
            MODE="alongside"
            say "Existing config found at $DEFAULT_TARGET: installing alongside (safe default)."
            say "Use --replace to take over \`nvim\` instead."
        fi
    else
        MODE="replace"
    fi
fi

if [[ "$MODE" == "replace" ]]; then
    [[ -z "$APPNAME" || "$APPNAME" == "nvim" ]] || die "--appname cannot be combined with --replace."
    APPNAME="nvim"
else
    APPNAME="${APPNAME:-loki}"
    [[ "$APPNAME" != "nvim" ]] || die "The name \"nvim\" is the default config. Use --replace for that."
    [[ "$APPNAME" =~ ^[A-Za-z0-9._-]+$ ]] || die "Invalid app name: $APPNAME"
fi

TARGET="$CONFIG_HOME/$APPNAME"
DATA_DIR="$DATA_HOME/$APPNAME"
STATE_DIR="$STATE_HOME/$APPNAME"
CACHE_DIR="$CACHE_HOME/$APPNAME"
INFO_FILE="$STATE_DIR/loki-install-info"
LAUNCHER=""
[[ "$MODE" == "alongside" ]] && LAUNCHER="$BIN_DIR/nvim-$APPNAME"
STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP=""

# --- Already installed? -----------------------------------------------------

ALREADY_LINKED=0
if [[ -e "$TARGET" && "$(readlink -f "$TARGET")" == "$SOURCE_DIR" ]]; then
    ALREADY_LINKED=1
    say "Already installed: $TARGET -> $SOURCE_DIR"
fi

if ((CLEAN_DATA)) && [[ "$MODE" != "replace" ]]; then
    say "Note: --clean-data only applies to --replace; ignoring it."
    CLEAN_DATA=0
fi

# --- Leftover data warning (replace mode only) ------------------------------

if [[ "$MODE" == "replace" && $ALREADY_LINKED -eq 0 ]]; then
    leftovers=("${PRE_EXISTING[@]}")
    if ((${#leftovers[@]})); then
        if ((CLEAN_DATA)); then
            say "Moving old plugin data aside (--clean-data):"
            for d in "${leftovers[@]}"; do
                say "  $d -> $d.backup.$STAMP"
                run mv "$d" "$d.backup.$STAMP"
            done
        else
            warn "Old Neovim data exists: ${leftovers[*]}"
            say "  Plugins and servers left by your previous setup can load under this config."
            say "  Re-run with --clean-data to move them aside, or use --alongside instead."
        fi
    fi
fi

# --- Safety copy of your personal files -------------------------------------
# lua/user/ is not in git. Save a copy before anything is linked or moved.

if [[ -x "$SOURCE_DIR/scripts/user-layer.sh" ]]; then
    if ((DRY_RUN)); then
        say "  [dry-run] would save a safety copy of your personal files (if you have any)"
    else
        "$SOURCE_DIR/scripts/user-layer.sh" backup || true
    fi
fi

# --- Link (with backup) -----------------------------------------------------

if ((ALREADY_LINKED == 0)); then
    if [[ -L "$TARGET" && ! -e "$TARGET" ]]; then
        say "Removing a broken link at $TARGET (it pointed to $(readlink "$TARGET"))"
        run rm "$TARGET"
    fi
    if [[ -e "$TARGET" || -L "$TARGET" ]]; then
        BACKUP="${TARGET}.backup.${STAMP}"
        say "Backing up existing config: $TARGET -> $BACKUP"
        run mv "$TARGET" "$BACKUP"
    fi
    run mkdir -p "$CONFIG_HOME"
    run ln -s "$SOURCE_DIR" "$TARGET"
    say "Linked $TARGET -> $SOURCE_DIR"
fi

# --- Launcher (alongside mode) ----------------------------------------------

LAUNCHER_STATUS=""
if [[ -n "$LAUNCHER" ]]; then
    if [[ -e "$LAUNCHER" ]] && ! grep -qF "$LAUNCHER_MARK" "$LAUNCHER" 2>/dev/null; then
        warn "$LAUNCHER exists and was not created by this installer; leaving it alone."
        LAUNCHER_STATUS="NOT created (file already exists): start with: NVIM_APPNAME=$APPNAME nvim"
    elif ((DRY_RUN)); then
        say "  [dry-run] write launcher $LAUNCHER"
        LAUNCHER_STATUS="$LAUNCHER"
    else
        mkdir -p "$BIN_DIR"
        printf '#!/usr/bin/env bash\n%s\nNVIM_APPNAME=%q exec nvim "$@"\n' "$LAUNCHER_MARK" "$APPNAME" >"$LAUNCHER"
        chmod +x "$LAUNCHER"
        LAUNCHER_STATUS="$LAUNCHER"
    fi
fi

# --- Record what happened (read by the first-run notice in Neovim) ----------

if ((ALREADY_LINKED == 0)); then
    if ((DRY_RUN)); then
        say "  [dry-run] write $INFO_FILE"
    else
        mkdir -p "$STATE_DIR"
        rm -f "$INFO_FILE.shown"
        {
            echo "mode=$MODE"
            echo "appname=$APPNAME"
            echo "config=$TARGET"
            echo "source=$SOURCE_DIR"
            echo "backup=$BACKUP"
            echo "launcher=$LAUNCHER"
            echo "date=$(date -Is)"
        } >"$INFO_FILE"
    fi
fi

# --- Summary ----------------------------------------------------------------

if [[ "$MODE" == "alongside" ]]; then
    START_CMD="nvim-$APPNAME"
else
    START_CMD="nvim"
fi

line="=============================================================================="
say
say "$line"
if ((DRY_RUN)); then
    say " DRY RUN: nothing was changed. This is what would happen:"
else
    say " Loki Neovim: done ($MODE)"
fi
say "$line"
say " Config   : $TARGET -> $SOURCE_DIR"
if [[ -n "$BACKUP" ]]; then
    if ((DRY_RUN)); then
        say " YOUR OLD CONFIG WOULD BE MOVED TO:"
    else
        say " YOUR OLD CONFIG WAS MOVED TO:"
    fi
    say "   $BACKUP"
elif [[ "$MODE" == "alongside" ]]; then
    say " Your existing Neovim config was not touched."
else
    say " Nothing needed backing up."
fi
[[ -n "$LAUNCHER_STATUS" ]] && say " Launcher : $LAUNCHER_STATUS"
say " Start it : $START_CMD   (first launch installs plugins; give it a minute)"
say " Verify   : :checkhealth loki"
say " Update   : $SOURCE_DIR/scripts/update.sh"
say " Undo     : $SOURCE_DIR/scripts/uninstall.sh"
say " Guide    : :LokiHelp inside Neovim (one screen); :LokiTutor to practice"
say " Keep     : $SOURCE_DIR - the config is a link to this folder and your personal"
say "            files (lua/user/) live inside it. Save them before deleting or"
say "            re-cloning it:  $SOURCE_DIR/scripts/user-layer.sh export"
say "$line"

if [[ -n "$LAUNCHER" ]]; then
    case ":$PATH:" in
        *":$BIN_DIR:"*) ;;
        *) warn "$BIN_DIR is not on your PATH, so \`nvim-$APPNAME\` will not be found."
           say "  Add this to your shell profile:  export PATH=\"$BIN_DIR:\$PATH\"" ;;
    esac
fi
