#!/usr/bin/env bash
# Undo scripts/install.sh: remove the link, restore your old config if one was
# backed up, and remove the launcher. Plugin data is left in place (it is listed
# at the end so you can delete it if you want a clean slate).
#
#   scripts/uninstall.sh              auto-detect (looks for "loki", the old name "elite", then "nvim")
#   scripts/uninstall.sh --appname X  target a specific install
#   scripts/uninstall.sh --dry-run    show what would happen
set -euo pipefail

SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
BIN_DIR="$HOME/.local/bin"
LAUNCHER_MARK="# Generated by the Loki Neovim installer"
LEGACY_LAUNCHER_MARK="# Generated by the Elite Neovim installer"   # installs made before the rename

APPNAME=""
DRY_RUN=0
ASSUME_YES=0

say()  { printf '%s\n' "$*"; }
warn() { printf 'WARNING: %s\n' "$*" >&2; }
die()  { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
run()  { if ((DRY_RUN)); then say "  [dry-run] $*"; else "$@"; fi; }

while (($#)); do
    case "$1" in
        --appname) shift; [[ $# -gt 0 ]] || die "--appname needs a value"; APPNAME="$1" ;;
        --dry-run) DRY_RUN=1 ;;
        -y|--yes)  ASSUME_YES=1 ;;
        -h|--help) sed -n '2,8p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *)         die "Unknown option: $1" ;;
    esac
    shift
done

say "== Loki Neovim uninstaller =="

# --- Find the install -------------------------------------------------------

if [[ -n "$APPNAME" ]]; then
    candidates=("$APPNAME")
else
    candidates=(loki elite nvim)
fi

TARGET=""
for name in "${candidates[@]}"; do
    t="$CONFIG_HOME/$name"
    if [[ -L "$t" && "$(readlink -f "$t")" == "$SOURCE_DIR" ]]; then
        APPNAME="$name"
        TARGET="$t"
        break
    fi
done

if [[ -z "$TARGET" ]]; then
    say "No symlink to $SOURCE_DIR found in $CONFIG_HOME."
    say "Nothing to uninstall. (If you cloned this repo straight into a config"
    say "folder, remove or rename that folder yourself.)"
    exit 0
fi

STATE_DIR="$STATE_HOME/$APPNAME"
INFO_FILE="$STATE_DIR/loki-install-info"
[[ -e "$INFO_FILE" || -e "$INFO_FILE.shown" ]] || INFO_FILE="$STATE_DIR/elite-install-info"   # pre-rename install record

read_info() {
    local key="$1" f
    for f in "$INFO_FILE" "$INFO_FILE.shown"; do
        if [[ -f "$f" ]]; then
            grep -m1 "^${key}=" "$f" | cut -d= -f2- || true
            return 0
        fi
    done
}

# --- Work out what to restore -----------------------------------------------

BACKUP=""
have_info=0
[[ -f "$INFO_FILE" || -f "$INFO_FILE.shown" ]] && have_info=1

if ((have_info)); then
    BACKUP="$(read_info backup || true)"
else
    shopt -s nullglob
    found=("$TARGET".backup.*)
    shopt -u nullglob
    if ((${#found[@]})); then
        BACKUP="${found[${#found[@]} - 1]}"
        warn "No install record found; the newest backup looks like: $BACKUP"
    fi
fi

if [[ -n "$BACKUP" && ! -e "$BACKUP" && ! -L "$BACKUP" ]]; then
    warn "Recorded backup no longer exists: $BACKUP"
    BACKUP=""
fi

say "This will:"
say "  - remove the link $TARGET -> $SOURCE_DIR"
if [[ -n "$BACKUP" ]]; then
    say "  - restore your old config from $BACKUP"
else
    say "  - restore nothing (no backup was made)"
fi
[[ -f "$BIN_DIR/nvim-$APPNAME" ]] && say "  - remove the launcher $BIN_DIR/nvim-$APPNAME (if this installer made it)"

if ((ASSUME_YES == 0 && DRY_RUN == 0)); then
    [[ -t 0 ]] || die "Not a terminal; re-run with --yes to confirm."
    read -r -p "Continue? [y/N] " answer
    [[ "$answer" =~ ^[Yy]$ ]] || { say "Cancelled. Nothing was changed."; exit 0; }
fi

# --- Do it ------------------------------------------------------------------

run rm "$TARGET"
if [[ -n "$BACKUP" ]]; then
    run mv "$BACKUP" "$TARGET"
    ((DRY_RUN)) || say "Restored: $TARGET"
fi

LAUNCHER="$BIN_DIR/nvim-$APPNAME"
if [[ -f "$LAUNCHER" ]] && { grep -qF "$LAUNCHER_MARK" "$LAUNCHER" 2>/dev/null || grep -qF "$LEGACY_LAUNCHER_MARK" "$LAUNCHER" 2>/dev/null; }; then
    run rm "$LAUNCHER"
    ((DRY_RUN)) || say "Removed launcher: $LAUNCHER"
fi

run rm -f "$INFO_FILE" "$INFO_FILE.shown"

say
say "Done."
if [[ "$APPNAME" == "nvim" ]]; then
    say "Plugin data in ~/.local/share|state|cache/nvim was left untouched (your"
    say "restored config uses the same folders)."
    shopt -s nullglob
    moved=("$DATA_HOME"/nvim.backup.* "$STATE_HOME"/nvim.backup.* "$CACHE_HOME"/nvim.backup.*)
    shopt -u nullglob
    if ((${#moved[@]})); then
        say "Old data set aside by --clean-data is still here; move it back if you want it:"
        for d in "${moved[@]}"; do say "  $d"; done
    fi
else
    say "Left in place (delete them yourself for a completely clean slate):"
    for d in "$DATA_HOME/$APPNAME" "$STATE_HOME/$APPNAME" "$CACHE_HOME/$APPNAME"; do
        if [[ -e "$d" ]]; then say "  $d"; fi
    done
fi
exit 0
